实际上tf.nn.embedding_lookup的作用就是找到要寻找的embedding data中的对应的行下的vector
![]( https://upload-images.jianshu.io/upload_images/1129359-51ec3c90c272f132.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/621/format/webp '示例')

In [4]:
import tensorflow as tf
import numpy as np

p = tf.Variable( tf.random_normal( [10,1] ) )
b = tf.nn.embedding_lookup( p, [1, 3] ) #查找张量中的序号为1和3的

In [ ]:
with tf.Session() as sess:
    sess.run( tf.global_variables_initializer() )
    print( 'b:', sess.run( b ) )
    print( 'p:', sess.run( p ) )

In [15]:
a = [[0.1, 0.2, 0.3], [1.1, 1.2, 1.3], [2.1, 2.2, 2.3], [3.1, 3.2, 3.3], [4.1, 4.2, 4.3]]
a = np.asarray( a )
idx1 = tf.Variable( [0, 2, 3, 1 ], tf.int32 )
idx2 = tf.Variable( [ [0, 2, 3, 1 ], [ 4, 0, 2, 2] ], tf.int32 )
out1 = tf.nn.embedding_lookup( a, idx1 )
out2 = tf.nn.embedding_lookup( a, idx2 )
init = tf.global_variables_initializer()

In [17]:
with tf.Session() as sess:
    sess.run( init )
    print( 'out1', sess.run( out1 ) )
    print( 'out2', sess.run( out2 ) )

out1 [[0.1 0.2 0.3]
 [2.1 2.2 2.3]
 [3.1 3.2 3.3]
 [1.1 1.2 1.3]]
out2 [[[0.1 0.2 0.3]
  [2.1 2.2 2.3]
  [3.1 3.2 3.3]
  [1.1 1.2 1.3]]

 [[4.1 4.2 4.3]
  [0.1 0.2 0.3]
  [2.1 2.2 2.3]
  [2.1 2.2 2.3]]]
